### ISSUE TITLE
Seems rather buggy and slow

### ISSUE THREAD

**Issue by Alkaris** [kirbo/rust-server-cli-rcon#1]
I was looking around for rcons for managing with Rust on Linux and just by rare chance I stumbled upon this to try it out. Very nice looking and simple to use. Upon using it seems to be rather slow and buggy for me.

Main issue is when a command has been issued it's slow at updating in the console, and often seems unresponsive, commands issued in this rcon CLI doesn't always seem to execute commands to the running server. I tried out few commands that the server has but seems to has no effect on the game while playing on the server.

**Comment by kirbo** [comment]
Sorry, this project was dead for a while, but I just recently resurrected this and few other projects related to Rust server. I will refactor this script at some point :)

**Comment by hamilton5** [comment]
It might just appear slow, because not all the last lines are shown... even if you page down.. you must have a big window/screen. There seems to be a problem with multi-lines and smaller widths...

**Comment by Alkaris** [comment]
> It might just appear slow, because not all the last lines are shown... even if you page down.. you must have a big window/screen. There seems to be a problem with multi-lines and smaller widths... I think this causes problems with the input box too? it does become unresponsive but a restart fixes.

this is outdated, and no it literally is slow and unresponsive, it would take more than a minute to update the console or respond to any commands.

**Comment by kirbo** [comment]
As @Alkaris said, this is outdated. I haven't even played Rust in a couple of years so none of my current Rust things might work anymore. I might be refactoring this tool at some point as well, as I did some refactoring with this https://github.com/kirbo/rust-server-tools as well.
