### ISSUE TITLE
 Error: ENOENT: no such file or directory, open '/dev/tty'

### ISSUE THREAD

**Issue by Owned67** [Kirbo/rust-server-cli-rcon#2]
node v10.15.1
npm 6.8.0
Windows 10 x64 pro

> C:\rust-server-cli-rcon>node index
> fs.js:115
>     throw err;
>     ^

> Error: ENOENT: no such file or directory, open '/dev/tty'
>     at Object.openSync (fs.js:439:3)
>     at Object.getInput (G:\GitHub\rust-server-cli-rcon\node_modules\terminal-kit\lib\tty.js:115:15)
>     at Object.get [as realTerminal] (G:\GitHub\rust-server-cli-rcon\node_modules\terminal-> > kit\lib\termkit.js:118:27)
>     at Object.<anonymous> (G:\GitHub\rust-server-cli-rcon\index.js:2:39)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)

**Comment by Kirbo** [comment]
This script is meant to run on Linux only, so sorry, no Windows support.
